update1

diff --git a/jenkinsFile b/jenkinsFile
--- a/jenkinsFile
+++ b/jenkinsFile
@@ -50,7 +50,7 @@ stages {
 					pwd; sudo chmod 777 build; ./build
 					
 				echo -e "\n\n**************************** This is a Deploy JOB $file **************************** "
-
+				if [[ -f "$file" ]]; then 
 				echo -e "\nSTEP 1: Deploying $file with default input........"
 				./$file -v -i <<<"5 400 500 600"
 
@@ -62,6 +62,12 @@ stages {
 				else  
 					  echo -e "**************** ERROR *********************\n"
 					  echo "Deployment failure - ABC.exe cannot be executed "
+					  echo -e "********************************************\n"
+					  exit 1
+				fi
+				else 
+					 echo -e "**************** ERROR *********************\n"
+					  echo "Build - ABC.exe notfound $file "
 					  echo -e "********************************************\n"
 					  exit 1
 				fi
@@ -78,8 +84,9 @@ stages {
 					pwd; sudo chmod 777 build; ./build
 					
 				echo -e "\n\n**************************** This is a Deploy JOB for $file**************************** "
+				if [[ -f "$file" ]]; then 
 				count=1
-
+				
 				for i in {1..10}
 				do
 					oe=$((1000 + RANDOM % 10000))
@@ -100,6 +107,12 @@ stages {
 					echo "-------------------------------------------------------------------"
 					((count++))
 				done
+				else 
+					 echo -e "**************** ERROR *********************\n"
+					  echo "Build - ABC.exe notfound $file "
+					  echo -e "********************************************\n"
+					  exit 1
+				fi
 				'''
 					}
 				}
