update

diff --git a/test b/test
--- a/test
+++ b/test
@@ -1,29 +1,37 @@
 #!/bin/bash
 set +x
 
-    pwd; sudo chmod 777 build; ./build
-    file=$(ls ABC* | sort -n | tail -1)
-    
-echo -e "\n\n**************************** This is a Deploy JOB for $file**************************** "
-count=1
+ file="$(pwd)/c_programs/ABC.exe"
+					[[ -f "$file" ]] && sudo rm -f "$file"
+					pwd; sudo chmod 777 build; ./build
+					
+				echo -e "\n\n**************************** This is a Deploy JOB for $file**************************** "
+				if [[ -f "$file" ]]; then 
+				count=1
+				
+				for i in {1..10}
+				do
+					oe=$((1000 + RANDOM % 10000))
+					fact=$((1 + RANDOM % 15))
+					num1=$((1 + RANDOM % 100))
+					num2=$((1 + RANDOM % 1000))
+					
+						echo -e "\n-------------------------- TEST_CASE ($count) --------------------------"
+						$file -v -i <<<"$fact $oe $num1 $num2"
+					
+					if [ $? -eq 0 ]; then
+						echo -e "\n      RESULT -> TEST_CASE (${count}): SUCCESS" 
+					else  
+						echo -e "\n      RESULT -> TEST_CASE (${count}): FAILED"
+						exit 1
+					fi
 
-for i in {1..10}
-do
-    oe=$((1000 + RANDOM % 10000))
-    fact=$((1 + RANDOM % 15))
-    num1=$((1 + RANDOM % 100))
-    num2=$((1 + RANDOM % 1000))
-    
-		echo -e "\n-------------------------- TEST_CASE ($count) --------------------------"
-		./$file -v -i <<<"$fact $oe $num1 $num2"
-    
-    if [ $? -eq 0 ]; then
-        echo -e "\n      RESULT -> TEST_CASE (${count}): SUCCESS" 
-    else  
-        echo -e "\n      RESULT -> TEST_CASE (${count}): FAILED"
-        exit 1
-    fi
-
-	echo "-------------------------------------------------------------------"
-	((count++))
-done
+					echo "-------------------------------------------------------------------"
+					((count++))
+				done
+				else 
+					 echo -e "**************** ERROR *********************\n"
+					  echo "Build - ABC.exe notfound $file "
+					  echo -e "********************************************\n"
+					  exit 1
+				fi
